In [8]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('popular_board_game.csv')
data

,name,category,playtime,playtime_num,avg_rating,num_ratings,min_players
0,Agricola,Economic,>90,150,7.98857,61557,1
1,Puerto Rico,Economic,>90,150,8.03590,61157,3
2,Small World,Fighting,"(60, 90]",80,7.29949,59211,2
3,Codenames,Deduction,<=30,15,7.71148,62563,2
4,Power Grid,Economic,>90,120,7.89004,54420,2
5,King of Tokyo,Fighting,<=30,30,7.23048,54881,2
6,Love Letter,Deduction,<=30,20,7.25253,53131,2
7,Splendor,Economic,<=30,30,7.47331,54445,2
8,Citadels,Bluffing,"(30, 60]",60,7.10124,46905,2
9,Dixit,Party Game,<=30,30,7.29405,47812,3
10,Race for the Galaxy,Economic,"(30, 60]",60,7.76240,44579,2
11,Scythe,Economic,>90,115,8.28410,52513,1
12,Terraforming Mars,Economic,>90,120,8.40331,57359,1
13,Munchkin,Fighting,>90,120,5.92127,39939,3
14,Arkham Horror,Fighting,>90,360,7.29157,36102,1
15,Dead of Winter: A Crossroads Game,Bluffing,>90,120,7.67747,37602,2
16,Terra Mystica,Economic,>90,150,8.19293,37276,2
17,Hanabi,Deduction,<=30,25,7.13730,36775,2
18,The Resistance,Bluffing,<=30,30,7.33418,34774,5
19,Battlestar Galactica: The Board Game,Bluffing,>90,300,7.74082,32005,3
20,Coup,Bluffing,<=30,15,7.03729,33927,2
21,Star Realms,Fighting,<=30,20,7.60884,33898,2
22,Magic: The Gathering,Fighting,<=30,20,7.47773,31086,2
23,Robinson Crusoe: Adventures on the Cursed Island,Fighting,>90,120,7.90738,31773,1
24,Blood Rage,Fighting,"(60, 90]",90,8.03108,31455,2
25,Caylus,Economic,>90,150,7.81108,26174,2
26,Gloomhaven,Fighting,>90,120,8.89906,37075,1
27,Tzolk'in: The Mayan Calendar,Economic,"(60, 90]",90,7.92748,28786,2
28,Android: Netrunner,Bluffing,"(30, 60]",45,7.89668,26001,2
29,Eclipse,Fighting,>90,180,7.94262,25542,2
...,...,...,...,...,...,...,...
214,Airlines Europe,Economic,"(60, 90]",75,7.32840,6681,2
215,Claustrophobia,Fighting,"(30, 60]",45,7.54728,6538,2
216,Finca,Economic,"(30, 60]",45,7.06826,6650,2
217,Rococo,Economic,>90,120,7.57887,7181,2
218,Lord of the Rings: The Confrontation,Bluffing,<=30,30,7.20778,6433,2
219,Flick 'em Up!,Fighting,"(30, 60]",45,7.02921,7258,2
220,Spartacus: A Game of Blood & Treachery,Fighting,>90,180,7.46593,6879,3
221,The Red Dragon Inn,Party Game,"(30, 60]",45,6.57217,6834,2
222,Tiny Epic Kingdoms,Bluffing,"(30, 60]",45,6.63359,6765,2
223,Pictionary,Party Game,"(60, 90]",90,5.81643,6615,3
224,Cockroach Poker,Bluffing,<=30,20,6.62477,7845,2
225,Forbidden Stars,Bluffing,>90,180,7.98764,7110,2
226,Dinosaur Island,Economic,>90,120,7.88547,9998,1
227,Yokohama,Economic,"(60, 90]",90,7.91106,7951,2
228,Wingspan,Economic,"(60, 90]",70,8.09865,32761,1
229,Exit: The Game â€“ The Abandoned Cabin,Deduction,>90,120,7.66760,7851,1
230,Fields of Arle,Economic,>90,120,8.13588,7415,1
231,Schotten Totten,Deduction,<=30,20,7.30702,6975,2
232,Dead of Winter: The Long Night,Bluffing,>90,120,7.76104,7271,2
233,Raptor,Fighting,<=30,25,7.40593,7236,2
234,Not Alone,Bluffing,"(30, 60]",45,7.07762,7249,2
235,KeyForge: Call of the Archons,Fighting,"(30, 60]",45,7.65602,8526,2
236,Xia: Legends of a Drift System,Fighting,>90,180,7.84598,6853,3
237,Brass: Birmingham,Economic,>90,120,8.60949,14551,2
238,Rajas of the Ganges,Economic,"(60, 90]",75,7.69465,7731,2
239,Decrypto,Deduction,"(30, 60]",45,7.80797,9659,3
240,Agricola (Revised Edition),Economic,>90,120,8.12485,7982,1
241,Chronicles of Crime,Deduction,"(60, 90]",90,8.03759,11684,1
242,Just One,Party Game,<=30,20,7.57741,8979,3
243,The Lord of the Rings: Journeys in Middle-earth,Fighting,>90,120,8.40100,6688,1

In [4]:
solo = data[data['min_players'] == 1].reset_index(drop=True)
no_solo = data[data['min_players'] > 1].reset_index(drop=True)

In [12]:
# Info needed: number of games in each category, game w/ highest num of ratings, average rating of games rounded to
# 2 decimal places, average playtime rounded to 2 dec places
# Also include gt username below bottom left of table, and save screenshot as table.png
ngames_solo = len(solo)
ngames_nosolo = len(no_solo)
highest_solo = solo.sort_values('num_ratings',ascending=False).loc[0,'name']
highest_nosolo = no_solo.sort_values('num_ratings',ascending=False).loc[0,'name']
avgrate_solo = round(np.mean(solo['avg_rating']),2)
avgrate_nosolo = round(np.mean(no_solo['avg_rating']),2)
avgtime_solo = round(np.mean(solo['playtime_num']),2)
avgtime_nosolo = round(np.mean(no_solo['playtime_num']),2)

solo_all = [ngames_solo,highest_solo,avgrate_solo,avgtime_solo]
nosolo_all = [ngames_nosolo,highest_nosolo,avgrate_nosolo,avgtime_nosolo]

In [15]:
solo_all,nosolo_all

([48, 'Agricola', 7.7, 117.5], [196, 'Puerto Rico', 7.28, 85.44])

In [21]:
df_data = pd.DataFrame({'Solo Supported':solo_all, 'Solo Not Supported':nosolo_all}).T
df_data.columns = ['Number of Games','Game with Most Ratings','Average Game Rating','Average Playtime']
df_data

,Number of Games,Game with Most Ratings,Average Game Rating,Average Playtime
Solo Supported,48,Agricola,7.7,117.5
Solo Not Supported,196,Puerto Rico,7.28,85.44